# -*- coding: utf-8 -*-
"""python_basics_vikas.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17-9t_WukOnsmSo-VZqRsYWKiHXhincjr
"""

name1 = input("Enter your name:")
age1 = int(input("Enter your age:"))
print(f"Your name is {name1} and your age is {age1}")
print(f"Age in months is: {age1 * 12}")
print(f"Age in days is: {age1 * 365}")
print(f"Age divided by 7  is: {age1 / 7}")
print(f"Age in months is: {age1 ** 2}")